version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    image: softy-pinko-front-end:task4
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252" # Map port 5252 in the container to the same port on the host
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: softy_pinko_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
