version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: task6-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end

  back-end:
    image: your-backend-image  # Replace with the actual image name
    container_name: task6-back-end
    ports:
      - "5252:5252"

  front-end:
    image: your-frontend-image  # Replace with the actual image name
    container_name: task6-front-end
    ports:
      - "3000:3000"
