version: '3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: your_frontend_image_name
    expose:
      - "9000"

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: your_backend_image_name
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: your_proxy_image_name
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
